name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Creer fichier .env
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo03_db" >> .env
          echo "DB_USER=labo03" >> .env
          echo "DB_PASS=labo03" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Ensure labo03-network exists
        run: docker network create labo03-network || true

      - name: Run tests inside container
        run: |
          docker compose down || true
          docker compose up -d mysql redis
          docker compose build store_manager
          docker compose run --rm store_manager python -m pytest -v tests

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Déployer en local
        run: |
          cd $GITHUB_WORKSPACE
          echo "Déploiement en cours"

          docker compose down || true
          docker compose up -d --build